export const CASES_GET_PRODUCTS = "CASES_GET_PRODUCTS";

export const CASES_GET_NEWS = "CASES_GET_NEWS";

export const CASES_GET_COLLECTIONS = "CASES_GET_COLLECTIONS";

export const CASES_GET_CONTACTS = "CASES_GET_CONTACTS";

export const CASES_GET_DATA = "CASES_GET_DATA";

export const CASES_GET_ONE_PRODUCT = "CASES_GET_ONE_PRODUCT";

export const CASES_GET_CART = "CASES_GET_CART";

export const CASES_GET_OFFER = "CASES_GET_OFFER";

export const CASES_GET_ABOUT_US = "CASES_GET_ABOUT_US";
