export const CASES_GET_PRODUCTS = "CASES_GET_PRODUCTS";

export const CASES_GET_NEWS = "CASES_GET_NEWS";

export const CASES_GET_COLLECTIONS = "CASES_GET_COLLECTIONS";

export const CASES_GET_CONTACTS = "CASES_GET_CONTACTS";

export const CASES_GET_DATA = "CASES_GET_DATA";

export const CASES_GET_ONE_PRODUCT = "CASES_GET_ONE_PRODUCT";
